[pytest]
# 命令行执行参数
;addopts = -capture=no -r sfE -vs --alluredir=./allure-result --clean-alluredir --tb=no --dist worksteal -n 10 --reruns 2 --reruns-delay 1
#addopts = -capture=no -r sfE -vs --alluredir=./allure-result --clean-alluredir --tb=no --reruns 3 --reruns-delay 0 --dist worksteal -n 6
#addopts = -capture=no -r sfE -vs --alluredir=./allure-result --clean-alluredir --reruns 1 --reruns-delay 0
#addopts = -capture=no -r sfE -vs --alluredir=./allure-result --tb=no --clean-alluredir --dist worksteal -n 10

# 过滤警告
filterwarnings =
    error
    ignore::UserWarning
    ignore:function ham\(\) is deprecated:DeprecationWarning

# 控制进度条显示
console_output_style = progress
cache_dir = .pytest-cache
