# HawkVAD 配置文件示例

# 输入文件路径
caselist=TestCase/caselist/PSTT/VadCase/FA_FR/FA.list
# 运行模式：0=单个音频文件, 1=音频列表文件, 2=目录
run_mode=1
# 并发任务数（仅在 run-mode=1 时有效）
jobs=20
# 采样率：8000 或 16000
sample-rate=16000
# VAD策略：0=low, 1=medium, 2=high
strategy=2
# VAD等级：0, 1, 2, 5
level=1
# 能量阈值
energy=50
# 静音转换长度
silence=400
# 语音转换长度
speech=70
# SNS列表输出文件名
snslist=silero_result.list
# 输出文件目录，可选
output=./silero_vad_output
# 文件类型支持：0=pcm&wave, 1=wave, 2=pcm
type=0
# 前置静音添加长度
left=0
# 后置静音添加长度
right=0
# VAD返回大小
return=10
# 任务类型：0=ASR, 1=WAKEUP
mode=0
# 峰值阈值
peak-threshold=0.1
# 低功耗模式
low-power=0
# 最小语音长度
min-speech-len=0
# 分块大小
chunk-size=16
# 模型资源路径
resource=TestResource/Resource/VAD/silero_vad

